# Generated by Django 4.0.1 on 2022-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zl7',
            name='fg3_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zl7',
            name='fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zl7',
            name='ft_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
