# Generated by Django 4.0.1 on 2022-03-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_zl7_fg3_pct_alter_zl7_fg_pct_alter_zl7_ft_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zl30',
            name='fg3_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zl30',
            name='fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zl30',
            name='ft_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zseason',
            name='fg3_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zseason',
            name='fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zseason',
            name='ft_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
