# Generated by Django 4.0.1 on 2022-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_zl30_fg3_pct_alter_zl30_fg_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='nameID',
            field=models.CharField(max_length=12),
        ),
    ]
