from django.db import models
# Create your models here.

class Player(models.Model):
    nameID = models.CharField(max_length = 12)
    name = models.CharField(max_length = 40)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)

class Season(models.Model):
    playerID = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)
    g = models.IntegerField()
    gs = models.IntegerField()
    mp_per_g = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg = models.DecimalField(max_digits = 3, decimal_places = 1)
    fga = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    fg3 = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3a = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    ft = models.DecimalField(max_digits = 3, decimal_places = 1)
    fta = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    trb = models.DecimalField(max_digits = 3, decimal_places = 1)
    ast = models.DecimalField(max_digits = 3, decimal_places = 1)
    stl = models.DecimalField(max_digits = 3, decimal_places = 1)
    blk = models.DecimalField(max_digits = 3, decimal_places = 1)
    tov = models.DecimalField(max_digits = 3, decimal_places = 1)
    pf = models.DecimalField(max_digits = 3, decimal_places = 1)
    pts = models.DecimalField(max_digits = 3, decimal_places = 1)

class L30(models.Model):
    playerID = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)
    g = models.IntegerField()
    gs = models.IntegerField()
    mp_per_g = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg = models.DecimalField(max_digits = 3, decimal_places = 1)
    fga = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    fg3 = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3a = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    ft = models.DecimalField(max_digits = 3, decimal_places = 1)
    fta = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    trb = models.DecimalField(max_digits = 3, decimal_places = 1)
    ast = models.DecimalField(max_digits = 3, decimal_places = 1)
    stl = models.DecimalField(max_digits = 3, decimal_places = 1)
    blk = models.DecimalField(max_digits = 3, decimal_places = 1)
    tov = models.DecimalField(max_digits = 3, decimal_places = 1)
    pf = models.DecimalField(max_digits = 3, decimal_places = 1)
    pts = models.DecimalField(max_digits = 3, decimal_places = 1)

class L7(models.Model):
    playerID = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)
    g = models.IntegerField()
    gs = models.IntegerField()
    mp_per_g = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg = models.DecimalField(max_digits = 3, decimal_places = 1)
    fga = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    fg3 = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3a = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    ft = models.DecimalField(max_digits = 3, decimal_places = 1)
    fta = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft_pct = models.DecimalField(max_digits = 4, decimal_places = 3)
    trb = models.DecimalField(max_digits = 3, decimal_places = 1)
    ast = models.DecimalField(max_digits = 3, decimal_places = 1)
    stl = models.DecimalField(max_digits = 3, decimal_places = 1)
    blk = models.DecimalField(max_digits = 3, decimal_places = 1)
    tov = models.DecimalField(max_digits = 3, decimal_places = 1)
    pf = models.DecimalField(max_digits = 3, decimal_places = 1)
    pts = models.DecimalField(max_digits = 3, decimal_places = 1)

class zSeason(models.Model):
    playerID = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)
    g = models.IntegerField()
    gs = models.IntegerField()
    mp_per_g = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3 = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    trb = models.DecimalField(max_digits = 3, decimal_places = 1)
    ast = models.DecimalField(max_digits = 3, decimal_places = 1)
    stl = models.DecimalField(max_digits = 3, decimal_places = 1)
    blk = models.DecimalField(max_digits = 3, decimal_places = 1)
    tov = models.DecimalField(max_digits = 3, decimal_places = 1)
    pts = models.DecimalField(max_digits = 3, decimal_places = 1)


class zL30(models.Model):
    playerID = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)
    g = models.IntegerField()
    gs = models.IntegerField()
    mp_per_g = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3 = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    trb = models.DecimalField(max_digits = 3, decimal_places = 1)
    ast = models.DecimalField(max_digits = 3, decimal_places = 1)
    stl = models.DecimalField(max_digits = 3, decimal_places = 1)
    blk = models.DecimalField(max_digits = 3, decimal_places = 1)
    tov = models.DecimalField(max_digits = 3, decimal_places = 1)
    pts = models.DecimalField(max_digits = 3, decimal_places = 1)


class zL7(models.Model):
    playerID = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    pos = models.CharField(max_length = 2)
    age = models.IntegerField()
    team_id = models.CharField(max_length = 7)
    g = models.IntegerField()
    gs = models.IntegerField()
    mp_per_g = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3 = models.DecimalField(max_digits = 3, decimal_places = 1)
    fg3_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft = models.DecimalField(max_digits = 3, decimal_places = 1)
    ft_pct = models.DecimalField(max_digits = 3, decimal_places = 1)
    trb = models.DecimalField(max_digits = 3, decimal_places = 1)
    ast = models.DecimalField(max_digits = 3, decimal_places = 1)
    stl = models.DecimalField(max_digits = 3, decimal_places = 1)
    blk = models.DecimalField(max_digits = 3, decimal_places = 1)
    tov = models.DecimalField(max_digits = 3, decimal_places = 1)
    pts = models.DecimalField(max_digits = 3, decimal_places = 1)

