# Generated by Django 4.0.1 on 2022-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_player_name_alter_player_nameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l30',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='l7',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='season',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='zl30',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='zl7',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='zseason',
            name='team_id',
            field=models.CharField(max_length=7),
        ),
    ]
